Bump test suite to current versions
jjjake/internetarchive pull request #627
Opened 2024-02-13 21:33 UTC by JustAnotherArchivist

CPython 3.7, PyPy 3.7, and PyPy 3.8 are EOL and unsupported.

The test on 3.12 currently fails. This is due to #613, and merging this PR should probably wait for #621 (or we should add a dependency on `setuptools` until that is resolved, as mentioned in <https://github.com/jjjake/internetarchive/issues/613#issuecomment-1872954045>).

2024-02-17 17:59 UTC, cclauss approved these changes

2024-02-19 06:39 UTC, cclauss requested changes
> we should add a dependency on `setuptools`

This is the correct solution because `distutils` was removed in Python 3.12 and the Python Packaging Authority recommends adding [`setuptools`](https://packaging.python.org/en/latest/key_projects/#distutils) to project dependencies.

2024-02-19 06:43 UTC, JustAnotherArchivist commented
Yeah, it's the correct solution – *if* we don't migrate away from `pkg_resources`. But the plan (#621) is to do so, and once that is merged, nothing here will depend on `setuptools` anymore at runtime. Thus the test on Python 3.12 will also work fine at that point (without any changes in this PR).

2024-02-19 06:50 UTC, cclauss commented
Yes.  #621 is a better approach.

2024-03-20 08:14 UTC, JustAnotherArchivist commented
Looks like this got obsoleted by e84edd1c although that did not remove the old PyPy versions. I'll create a new PR for that instead.

2024-03-20 08:14 UTC, closed without merging